cc = ''  #Cedula ciudadania
nameClient = '' #Nombre del Cliente
email = '' # Email
idProd =''  # Id producto
quantity = '' # Cantidad
price = '' # Precio
nameProd = '' #Nombre de producto
invoice_num = '' #Numero de factura
invoice_date = '' #Fecha de factura
searchId = '' #Variable para buscar en el inventario
